[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/admin-guard"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/get-all-data"
  to = "/.netlify/functions/get-all-data"
  status = 200

[[redirects]]
  from = "/.netlify/functions/update-ai"
  to = "/.netlify/functions/update-ai"
  status = 200

[[redirects]]
  from = "/.netlify/functions/send-reply"
  to = "/.netlify/functions/send-reply"
  status = 200

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://static.hsappstatic.net https://fonts.googleapis.com https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self'; frame-src 'self' https://meetings.hubspot.com https://meetings-na2.hubspot.com"

